apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calculator-ce
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/DaAlbrecht/ArgoCD-demo.git
    targetRevision: HEAD
    path: kustomization

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
