apiVersion: v1
kind: Secret
metadata:
  name: k8s-training-credentials
  namespace: training
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJkZXZvcHMuaXNzLWFnLmNoOjUwNTAiOiB7CiAgICAgICJ1c2VybmFtZSI6ICJrOHMtdHJhaW5pbmciLAogICAgICAicGFzc3dvcmQiOiAiZE1yblcxd2dpM0U2S3V1MjFzdnQiLAogICAgICAiZW1haWwiOiAiZGF2aWQuYWxicmVjaHRAaXNzLWFnLmNoIiwKICAgICAgImF1dGgiOiAiYXpoekxYUnlZV2x1YVc1bk9tUk5jbTVYTVhkbmFUTkZOa3QxZFRJeGMzWjAiCiAgICB9CiAgfQp9Cg==
